name: Second Workflow
on: workflow_dispatch:
jobs:
  hello-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: "Welcome"
        run: echo "Welcome to second workflow in git"
  bye-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: "Bye"
        run: echo "Bye from second workflow in git"      